### ISSUE TITLE
docker always restart

### ISSUE THREAD

**Issue by iSwiftLiu** [allanjamesvestal/Cousin-IDDD#1]
Hello, it seems doesn't work.
logs is
```
Observer Stopped
Watching...
Observer Stopped
Watching...
Observer Stopped
Watching...
Observer Stopped
Watching...
Observer Stopped
Watching...
Observer Stopped
Watching...
Observer Stopped
Watching...
Observer Stopped
Watching...
Observer Stopped
Watching...
Observer Stopped
```

```
services:
  cousin-iddd:
    image: iddd
    environment:
      - NAVIDROME_HOST=ip:4533
      - NAVIDROME_USERNAME=admin
      - NAVIDROME_PASSWORD=password
      - PODGRAB_HOST=ip:4534
      - PODGRAB_USERNAME=podgrab
      - PODGRAB_PASSWORD=password
    restart: always
    volumes:
      - ./config:/config
      - ./logs:/logs
      - /data/docker-podgrab/assets:/watched_media
```
docker-compose ps
restarting
